function(nsw_add_test name)
    add_executable(${name} ${name}.cpp)
    target_link_libraries(${name} PRIVATE nutsweller_dsp)
    target_include_directories(${name} PRIVATE ${CMAKE_SOURCE_DIR}/src ${CMAKE_CURRENT_SOURCE_DIR})
    add_test(NAME ${name} COMMAND ${name})
endfunction()

nsw_add_test(test_pitch_detector)
nsw_add_test(test_shifter)
nsw_add_test(test_parameters)
